# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Github Metrics
on:
  # Schedule updates (daily)
  schedule: [{cron: "0 0 * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["main"]}
jobs:
  generate-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          config_timezone: Asia/Jakarta
          template: repository
          user: Febry
          base: header, repositories
          plugin_introduction: yes
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: X
